#! /bin/sh

dir=`pwd`
PROJNAME=`basename $dir`

ADT_HOME=/opt/adt

if [ ! -d ${ADT_HOME} ]
then
    echo "can't find ADT at ${ADT_HOME}"
    exit 1
fi

android=${ADT_HOME}/sdk/tools/android

target=`$android list targets --compact | tail -1`

(
    echo "# this files is included in both shell scripts and Makefiles"
    echo "ADT_HOME=${ADT_HOME}"
    echo "PROJNAME=${PROJNAME}"
) > conf.sh

echo "# run this:"
echo "$android create project \
--target ${target} \
--name ${PROJNAME} \
--path . \
--activity MainActivity \
--package org.willisson.${PROJNAME}"


vers=`echo $target | sed 's/.*-//'`

echo ""
echo "# then add this to AndroidManifest.xml:"
echo "<uses-sdk android:minSdkVersion='${vers}' \
 android:targetSdkVersion='${vers}' />"

echo ""
echo "# to see possible targets:"
echo "$android list targets"

