#! /bin/sh

dir=`pwd`
projname=`basename $dir`

ADT_HOME=/opt/adt

if [ ! -d ${ADT_HOME} ]
then
    echo "can't find ADT at ${ADT_HOME}"
    exit 1
fi

android=${ADT_HOME}/sdk/tools/android

target=`$android list targets --compact | tail -1`

echo "# run this:"
echo "$android create project \
--target ${target} \
--name ${projname} \
--path . \
--activity MainActivity \
--package org.willisson.${projname}"


vers=`echo $target | sed 's/.*-//'`

echo ""
echo "# then add this to AndroidManifest.xml:"
echo "<uses-sdk android:minSdkVersion='${vers}' \
 android:targetSdkVersion='${vers}' />"

echo ""
echo "# to see possible targets:"
echo "$android list targets"

